name: hymate_test
description: "HyMate Test App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.6
  fl_chart: 0.68.0
  equatable: 2.0.5
  dio: 5.4.3+1
  pretty_dio_logger: 1.3.1
  json_annotation: 4.9.0
  fpdart: 1.1.0
  intl: 0.19.0
  calendar_date_picker2: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 6.8.0
  build_runner: 2.4.6
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true
  assets:
    - test_data/hymate_hierarchy.json
